substitutions:
  name: "dak-keg-display"
  friendly_name: "Dak Keg Display"
  project_name: "Dak Enterprises.Dak Keg Display"
  project_version: "0.0.1"
  ble_server_mac: "FF:FF:FF:FF:FF:FF" # **** Udpate with Scale BLE MAC Address ****
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

packages:
  basescale: !include common/ble_client_base.yaml
