substitutions:
  name: "dak-keg-display"
  friendly_name: "Dak Keg Display"
  project_name: "Dak Enterprises.Dak Keg Display"
  project_version: "0.0.1"

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

packages:
  basescale: !include common/ble_client_base.yaml
