substitutions:
  name: "dak-keg-display"
  friendly_name: "Dak Keg Display"
  project_name: "Dak Enterprises.Dak Keg Display"
  project_version: "0.0.1"
  #Enter Scale BLE Mac Address Here
  ble_server_mac: "XX:XX:XX:XX:XX:XX" 
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

packages:
  basescale: !include common/ble_client_base.yaml
